export const CATEGORIES = [
  { id: 'hvac', name: 'HVAC', icon: '🌬️', color: '#00C9A7' },
  { id: 'plumbing', name: 'Plumbing', icon: '🔧', color: '#2A6DD9' },
  { id: 'exterior', name: 'Exterior', icon: '🏡', color: '#1DB954' },
  { id: 'electrical', name: 'Electrical', icon: '⚡', color: '#FFB300' },
  { id: 'safety', name: 'Safety', icon: '🛡️', color: '#FF7043' },
  { id: 'insurance', name: 'Insurance', icon: '📋', color: '#00BCD4' },
  { id: 'pest', name: 'Pest Control', icon: '🐜', color: '#8BC34A' },
  { id: 'irrigation', name: 'Irrigation', icon: '💧', color: '#29B6F6' },
  { id: 'weather', name: 'Weather Emergency', icon: '🌪️', color: '#FF5252' },
]

export const getCategory = (id) => CATEGORIES.find((c) => c.id === id) || CATEGORIES[0]

export const FREQUENCIES = ['Monthly', 'Quarterly', 'Seasonal', 'Annual', 'One-time']

export const REGIONS = [
  { id: 'southeast', name: 'Florida / Southeast' },
  { id: 'midwest', name: 'Midwest' },
  { id: 'northeast', name: 'Northeast' },
  { id: 'northwest', name: 'Pacific Northwest' },
  { id: 'southwest', name: 'Southwest' },
  { id: 'west', name: 'West / California' },
]

export const TASK_TEMPLATES = {
  hvac: {
    title: 'HVAC Maintenance',
    icon: '🌬️',
    tips: 'Your HVAC system should be serviced twice a year — once before cooling season and once before heating season. Regular maintenance extends equipment life and lowers energy bills.',
    tasks: [
      { title: 'Replace Air Filter', frequency: 'Monthly', notes: 'Check filter monthly and replace every 1-3 months depending on filter type and pets/allergies. A dirty filter strains the system and reduces air quality.' },
      { title: 'Annual HVAC Tune-Up (Cooling)', frequency: 'Annual', notes: 'Schedule a professional inspection each spring before summer heat hits. Technician checks refrigerant, coils, electrical connections, and thermostat calibration.' },
      { title: 'Annual HVAC Tune-Up (Heating)', frequency: 'Annual', notes: 'Schedule a professional inspection each fall before winter. Technician checks heat exchanger, burners, and safety controls.' },
      { title: 'Clean AC Condensate Drain Line', frequency: 'Quarterly', notes: 'Pour a cup of diluted bleach or vinegar down the drain line to prevent clogs and mold buildup. A clogged drain can cause water damage.' },
      { title: 'Clear Debris Around Outdoor Unit', frequency: 'Seasonal', notes: 'Keep at least 2 feet of clearance around the outdoor condenser unit. Remove leaves, grass clippings, and debris that restrict airflow.' },
      { title: 'Test Thermostat', frequency: 'Seasonal', notes: 'Test heating and cooling modes at each season change. Replace batteries in programmable thermostats annually.' },
    ],
  },
  plumbing: {
    title: 'Plumbing',
    icon: '🔧',
    tips: 'Plumbing issues are among the most costly home repairs. Regular inspections catch small leaks before they become major water damage.',
    tasks: [
      { title: 'Check for Leaks Under Sinks', frequency: 'Monthly', notes: 'Inspect under all sinks for moisture, drips, or staining. Early detection prevents mold and cabinet damage.' },
      { title: 'Test Water Pressure', frequency: 'Quarterly', notes: 'Normal water pressure is 40-80 PSI. High pressure stresses pipes and appliances. Install a pressure gauge on an outdoor hose bib to check.' },
      { title: 'Flush Water Heater', frequency: 'Annual', notes: 'Drain 1-2 gallons from the water heater to remove sediment buildup. Sediment reduces efficiency and shortens tank life. Most tanks last 8-12 years.' },
      { title: 'Inspect Toilet for Running Water', frequency: 'Quarterly', notes: 'Add food coloring to the tank — if color appears in the bowl without flushing, the flapper needs replacing. A running toilet wastes up to 200 gallons per day.' },
      { title: 'Clean Showerhead and Faucet Aerators', frequency: 'Annual', notes: 'Soak in vinegar to dissolve mineral deposits. Clogged aerators reduce water flow and pressure.' },
      { title: 'Locate and Label Water Shutoff Valves', frequency: 'Annual', notes: 'Know where your main shutoff and individual fixture shutoffs are. In a leak emergency, quick shutoff saves thousands in damage.' },
    ],
  },
  exterior: {
    title: 'Exterior',
    icon: '🏡',
    tips: 'Your home\'s exterior is its first line of defense against weather. Regular inspection and maintenance prevents water intrusion, structural damage, and costly repairs.',
    tasks: [
      { title: 'Inspect Roof for Damage', frequency: 'Annual', notes: 'Look for missing, cracked, or curling shingles. Check flashing around chimneys, vents, and skylights. Best done after major storms. Hire a professional for a thorough inspection every 3-5 years.' },
      { title: 'Clean Gutters and Downspouts', frequency: 'Seasonal', notes: 'Clear gutters of leaves and debris each spring and fall. Clogged gutters cause water to back up under roofing and damage fascia. Ensure downspouts direct water at least 6 feet from foundation.' },
      { title: 'Inspect and Caulk Windows and Doors', frequency: 'Annual', notes: 'Check caulk and weatherstripping around all windows and doors. Cracked or missing caulk allows water and air infiltration, increasing energy costs.' },
      { title: 'Pressure Wash Exterior', frequency: 'Annual', notes: 'Clean siding, driveway, walkways, and deck to remove dirt, mold, and mildew. Prevents long-term staining and deterioration.' },
      { title: 'Inspect Foundation for Cracks', frequency: 'Annual', notes: 'Walk around the foundation looking for new or widening cracks. Horizontal cracks are more serious than vertical ones. Fill small cracks with hydraulic cement or epoxy.' },
      { title: 'Check Driveway and Walkways', frequency: 'Annual', notes: 'Fill cracks in concrete or asphalt to prevent water from expanding them. Seal asphalt driveways every 2-3 years.' },
    ],
  },
  electrical: {
    title: 'Electrical',
    icon: '⚡',
    tips: 'Electrical issues are a leading cause of house fires. Never ignore flickering lights, tripping breakers, or burning smells — these require immediate professional attention.',
    tasks: [
      { title: 'Test GFCI Outlets', frequency: 'Monthly', notes: 'Press the "Test" button on GFCI outlets in bathrooms, kitchen, garage, and outdoors. The outlet should lose power. Press "Reset" to restore. Replace any that don\'t trip or reset.' },
      { title: 'Test Arc Fault Circuit Interrupters (AFCIs)', frequency: 'Quarterly', notes: 'AFCIs protect against electrical fires from damaged wiring. Test using the Test button on the breaker. Required in bedrooms by modern code.' },
      { title: 'Inspect Electrical Panel', frequency: 'Annual', notes: 'Look for signs of corrosion, burnt smells, or double-tapped breakers. Have a licensed electrician inspect the panel every 5-10 years or if you notice any issues.' },
      { title: 'Check Outdoor Outlets and Lighting', frequency: 'Seasonal', notes: 'Inspect outdoor outlets for moisture damage and ensure covers are properly sealed. Check that exterior lighting is working and bulbs are weather-rated.' },
      { title: 'Inspect Extension Cords and Power Strips', frequency: 'Annual', notes: 'Replace any cords with frayed insulation, bent prongs, or damaged connectors. Never run extension cords under rugs or through walls. Use surge protectors for electronics.' },
    ],
  },
  safety: {
    title: 'Safety',
    icon: '🛡️',
    tips: 'Working smoke and carbon monoxide detectors save lives. Keep emergency supplies stocked and make sure every family member knows your home\'s emergency plan.',
    tasks: [
      { title: 'Test Smoke Detectors', frequency: 'Monthly', notes: 'Press and hold the test button until the alarm sounds. Replace batteries annually (or use 10-year sealed battery models). Replace the entire unit every 10 years.' },
      { title: 'Test Carbon Monoxide Detectors', frequency: 'Monthly', notes: 'Test using the test button. CO detectors should be on every level and near sleeping areas. Replace every 5-7 years — they have a chemical sensor that degrades over time.' },
      { title: 'Check Fire Extinguisher', frequency: 'Annual', notes: 'Verify the pressure gauge needle is in the green zone. Check for physical damage or corrosion. Have it professionally inspected every 6 years and replaced or recharged as needed.' },
      { title: 'Review Home Emergency Plan', frequency: 'Annual', notes: 'Ensure all family members know two exit routes from every room, the meeting point outside, and emergency contacts. Practice a fire drill with children.' },
      { title: 'Inspect Door and Window Locks', frequency: 'Quarterly', notes: 'Test all locks for smooth operation. Lubricate with graphite spray if stiff. Consider upgrading to deadbolts if not already installed.' },
      { title: 'Check Emergency Supply Kit', frequency: 'Annual', notes: 'Restock water (1 gallon per person per day for 3 days), food, flashlights, batteries, first aid kit, medications, and important documents. Check expiration dates.' },
    ],
  },
  insurance: {
    title: 'Insurance',
    icon: '📋',
    tips: 'Your homeowner\'s insurance policy should reflect the actual replacement cost of your home and belongings. Review it annually and after any major improvements.',
    tasks: [
      { title: 'Review Homeowner\'s Insurance Policy', frequency: 'Annual', notes: 'Compare your coverage limits to current rebuilding costs in your area. Costs have risen significantly — many homeowners are underinsured. Contact your agent to discuss coverage gaps.' },
      { title: 'Update Home Inventory', frequency: 'Annual', notes: 'Walk through your home and document valuables with photos or video. Store the inventory in the cloud or off-site. This is essential for filing accurate claims after theft or disaster.' },
      { title: 'Review Flood Insurance', frequency: 'Annual', notes: 'Standard homeowner\'s policies do NOT cover flooding. Check your flood zone status (FEMA\'s flood map) and consider NFIP or private flood insurance, especially in coastal or low-lying areas.' },
      { title: 'Check Deductibles and Riders', frequency: 'Annual', notes: 'Confirm your deductible amounts for standard claims vs. named-storm or wind events. Add scheduled personal property riders for jewelry, art, or electronics that exceed standard limits.' },
    ],
  },
  pest: {
    title: 'Pest Control',
    icon: '🐜',
    tips: 'Prevention is far cheaper than treatment. Seal entry points, eliminate moisture, and maintain a pest control schedule before infestations take hold.',
    tasks: [
      { title: 'Quarterly Pest Control Treatment', frequency: 'Quarterly', notes: 'Schedule professional perimeter treatment every 3 months. Covers common pests: ants, roaches, spiders, and rodents. More frequent treatment may be needed in humid climates.' },
      { title: 'Inspect for Termites', frequency: 'Annual', notes: 'Look for mud tubes along foundation, hollow-sounding wood, or discarded wings near windows. Annual professional termite inspection is strongly recommended, especially in the South.' },
      { title: 'Seal Entry Points', frequency: 'Annual', notes: 'Caulk gaps around pipes, wires, and conduits where they enter the home. Install door sweeps and repair damaged screens. Even a dime-sized gap can let mice in.' },
      { title: 'Check for Moisture Issues', frequency: 'Seasonal', notes: 'Pests thrive where moisture collects. Fix leaky pipes, ensure proper drainage away from foundation, and use a dehumidifier in crawl spaces or basements.' },
      { title: 'Rodent Prevention Check', frequency: 'Seasonal', notes: 'Look for droppings, gnaw marks, or nesting materials in attic, garage, and under sinks. Set traps proactively in fall when rodents seek warmth indoors.' },
    ],
  },
  irrigation: {
    title: 'Irrigation',
    icon: '💧',
    tips: 'A properly maintained irrigation system uses up to 50% less water than manual watering. Regular checks prevent leaks that can dramatically increase your water bill.',
    tasks: [
      { title: 'Inspect Sprinkler Heads', frequency: 'Monthly', notes: 'Check for clogged, broken, or misaligned heads. A broken sprinkler head wastes hundreds of gallons per month. Adjust heads to avoid watering sidewalks and driveways.' },
      { title: 'Check Controller/Timer Settings', frequency: 'Seasonal', notes: 'Adjust watering schedules each season. Water deeply and infrequently (2-3 times per week in summer, less in cooler months). Most systems over-water when left on default settings.' },
      { title: 'Inspect Drip Lines and Emitters', frequency: 'Quarterly', notes: 'Check drip irrigation emitters for clogs or damage. Flush the system periodically. Replace emitters that are cracked or delivering uneven water flow.' },
      { title: 'Winterize Irrigation System', frequency: 'Annual', notes: 'Blow out all water from lines before first freeze to prevent pipe bursts. Relevant for Midwest and Northeast — not required in Florida/Southeast.' },
      { title: 'Spring System Startup', frequency: 'Annual', notes: 'Turn system back on slowly after winter. Check all zones for proper coverage. Test the rain sensor to ensure it shuts off the system during rainfall.' },
    ],
  },
  weather: {
    title: 'Weather Emergency',
    icon: '🌪️',
    tips: 'Preparation before a weather emergency is the difference between minor inconvenience and major loss. Have a plan, know your risks, and don\'t wait until a storm is imminent.',
    tasks: [],
    regional: {
      southeast: {
        name: 'Florida / Southeast — Hurricane Prep',
        tips: 'Hurricane season runs June 1 through November 30. The time to prepare is before a storm is named — not when it\'s 48 hours away.',
        tasks: [
          { title: 'Hurricane Season Kickoff Inspection', frequency: 'Annual', notes: 'Each May, inspect shutters/panels, generator, fuel supply, and emergency kit. Test the generator under load. Confirm your insurance covers wind and flood events.' },
          { title: 'Install/Inspect Hurricane Shutters or Impact Windows', frequency: 'Annual', notes: 'Ensure all shutters are in working order and hardware is not corroded. Know which panels go where before a storm warning is issued. Impact windows require no action but inspect for seal integrity.' },
          { title: 'Trim Trees and Shrubs', frequency: 'Seasonal', notes: 'Trim dead branches and overhanging limbs before hurricane season (May) and again mid-season. Flying debris is the #1 cause of storm damage.' },
          { title: 'Test and Fuel Generator', frequency: 'Seasonal', notes: 'Run your generator monthly under load. Store enough fuel for 5-7 days. Rotate fuel with a stabilizer. Never run a generator indoors or in the garage.' },
          { title: 'Stock Hurricane Emergency Supplies', frequency: 'Annual', notes: 'Minimum 7-day supply: water (1 gal/person/day), non-perishable food, medications, battery/hand-crank radio, flashlights, cash, phone chargers, important documents in waterproof bag.' },
          { title: 'Review Evacuation Routes', frequency: 'Annual', notes: 'Know your county\'s evacuation zones (check local emergency management website). Identify two evacuation routes and a destination. Pre-register pets if sheltering with animals.' },
          { title: 'Secure Outdoor Furniture and Items', frequency: 'Seasonal', notes: 'Before any named storm, bring all outdoor furniture, grills, planters, and decorations inside or secure with straps. Unsecured items become dangerous projectiles at hurricane wind speeds.' },
          { title: 'Check Garage Door Bracing', frequency: 'Annual', notes: 'Garage doors are the most vulnerable point in a hurricane. Ensure your door is rated for high winds or install a bracing kit. An un-braced door can fail and cause the roof to lift.' },
          { title: 'Inspect Roof and Attic', frequency: 'Annual', notes: 'Hire a roofer to inspect before hurricane season. Ensure all shingles, tiles, and flashing are secure. Check attic for proper hurricane straps connecting roof structure to walls.' },
          { title: 'Document Home and Belongings', frequency: 'Annual', notes: 'Walk through with video before hurricane season begins. Store video in cloud storage. Essential for insurance claims after storm damage.' },
        ],
      },
      midwest: {
        name: 'Midwest — Tornado & Winter Storm Prep',
        tips: 'The Midwest faces tornado season (spring/summer) and severe winter storms. Prepare for both and know your local warning systems.',
        tasks: [
          { title: 'Test Tornado Safe Room or Shelter', frequency: 'Annual', notes: 'Locate your safest shelter area (lowest floor, interior room, away from windows). Stock it with a battery radio, flashlight, water, and shoes. Know the difference between a Tornado Watch and Warning.' },
          { title: 'Register for Local Emergency Alerts', frequency: 'Annual', notes: 'Sign up for your county\'s Wireless Emergency Alerts and text/email notification system. Have a NOAA weather radio with battery backup in your home.' },
          { title: 'Inspect Sump Pump Before Spring', frequency: 'Annual', notes: 'Test sump pump each March by pouring water into the pit. Clean the inlet screen. Consider a battery backup sump pump for power outage protection during heavy spring rains.' },
          { title: 'Winterize Exterior Pipes and Faucets', frequency: 'Annual', notes: 'Before first freeze (October/November), disconnect and drain garden hoses. Shut off and drain exterior faucet lines. Insulate pipes in unheated spaces like garages and crawl spaces.' },
          { title: 'Stock Winter Emergency Supplies', frequency: 'Annual', notes: 'Keep in your home: rock salt, snow shovel, ice melt, battery-powered carbon monoxide detector, extra blankets, backup heating source (approved for indoor use), 3-day food and water supply.' },
          { title: 'Stock Winter Car Emergency Kit', frequency: 'Annual', notes: 'Keep in each vehicle: ice scraper, jumper cables, blanket, sand or kitty litter for traction, small shovel, flashlight, and energy bars. Check antifreeze and tire pressure as temperatures drop.' },
          { title: 'Service Snowblower Before Winter', frequency: 'Annual', notes: 'Each October, change the oil, replace spark plugs, check belts and skid plates, and add fuel stabilizer. A snowblower that won\'t start during a blizzard is useless.' },
          { title: 'Inspect and Clean Fireplace/Chimney', frequency: 'Annual', notes: 'Have chimney professionally cleaned and inspected before heating season. Creosote buildup is a leading cause of house fires. Install a chimney cap to keep animals and debris out.' },
          { title: 'Check Attic Insulation and Ventilation', frequency: 'Annual', notes: 'Proper attic insulation prevents ice dams — ridges of ice that form at the roof edge and back water under shingles. Ensure attic vents are clear and insulation is at least R-49 in cold climates.' },
        ],
      },
      northeast: {
        name: 'Northeast — Winter Storm & Nor\'easter Prep',
        tips: 'Nor\'easters, ice storms, and heavy snowfall are major threats. Prepare your home before Thanksgiving — once storms hit, it\'s too late.',
        tasks: [
          { title: 'Winterize Pipes Before First Freeze', frequency: 'Annual', notes: 'Insulate pipes in attics, crawl spaces, and exterior walls. Know where your main water shutoff is. Keep cabinet doors under sinks open during extreme cold to let warm air reach pipes.' },
          { title: 'Inspect Roof for Snow Load Capacity', frequency: 'Annual', notes: 'Have your roof inspected before winter. Know the snow load limit. After heavy snowfall (over 6 inches of wet snow), consider a roof rake to reduce weight. A collapsed roof is a life-safety emergency.' },
          { title: 'Check Heating System Before Winter', frequency: 'Annual', notes: 'Service oil, gas, or propane heating system each October. Replace filters, check fuel supply, and test emergency shutoff. Schedule delivery before demand peaks and prices rise.' },
          { title: 'Stock Heating Fuel Supply', frequency: 'Annual', notes: 'Order oil or propane before October. Keep tank at least half full throughout winter. Know your average burn rate so you don\'t run out during a storm when delivery may be delayed.' },
          { title: 'Ice Dam Prevention', frequency: 'Annual', notes: 'Ensure attic is properly insulated and ventilated to keep roof surface cold and prevent uneven melting. Install heat cables in problem areas. After major snowfall, use a roof rake to remove snow from the first 3-4 feet of roof edge.' },
          { title: 'Service Snowblower Before Winter', frequency: 'Annual', notes: 'Each October, change the oil, replace spark plugs, check belts and impeller, and add fuel stabilizer. Test run before the first storm. Keep extra shear pins on hand.' },
          { title: 'Inspect and Clean Chimney', frequency: 'Annual', notes: 'Have chimney professionally swept and inspected before heating season. Creosote and bird nests are fire hazards. Install a chimney cap and damper if not already in place.' },
          { title: 'Prepare Nor\'easter Emergency Kit', frequency: 'Annual', notes: 'Stock: 3-7 day food and water supply, battery/hand-crank radio, flashlights, extra batteries, blankets, backup battery packs, cash, and a manual can opener. Fill prescriptions before major storms.' },
          { title: 'Check Generator and Alternative Heat', frequency: 'Annual', notes: 'Test generator under load before winter. Stock fuel with stabilizer. Have an approved indoor-safe alternative heat source (propane heater with proper ventilation). Never use generators or charcoal indoors.' },
          { title: 'Inspect Foundation and Basement for Water Entry', frequency: 'Annual', notes: 'Check basement walls and floor for cracks before spring thaw. Apply waterproofing sealant to minor cracks. Ensure sump pump is working and has a battery backup for storm power outages.' },
        ],
      },
      northwest: {
        name: 'Pacific Northwest — Rain, Wind & Wildfire Prep',
        tips: 'The Pacific Northwest faces heavy rain and windstorms in winter and increasingly severe wildfire smoke in summer. Prepare for both wet and dry season threats.',
        tasks: [
          { title: 'Inspect Roof and Gutters Before Rainy Season', frequency: 'Annual', notes: 'Clean gutters each October before the rainy season begins. Check roof for missing shingles or damaged flashing. The PNW\'s heavy rainfall means clogged gutters quickly cause water intrusion and rot.' },
          { title: 'Check Sump Pump and Drainage', frequency: 'Annual', notes: 'Test sump pump each fall by pouring water into the pit. Ensure downspouts direct water at least 6 feet from the foundation. PNW soils can become saturated quickly, causing basement flooding.' },
          { title: 'Prepare for Wind Storms', frequency: 'Annual', notes: 'Trim dead branches and trees that overhang the home before fall. Secure outdoor furniture and decorations. Know which utility poles serve your home for faster outage reporting.' },
          { title: 'Stock Power Outage Emergency Kit', frequency: 'Annual', notes: 'PNW windstorms frequently knock out power for days. Stock: 3-7 day food and water supply, battery/hand-crank radio, flashlights, battery packs, propane camp stove for outdoor cooking, and extra blankets.' },
          { title: 'Wildfire Smoke Preparedness', frequency: 'Annual', notes: 'Each June, check that HVAC filters are rated MERV-13 or higher. Stock N95 respirators. Seal window gaps with weatherstripping. Know your local air quality index (AQI) resources. Create a clean room in the home.' },
          { title: 'Defensible Space for Wildfire Risk', frequency: 'Annual', notes: 'If in a wildfire-prone area (east of the Cascades or rural areas), clear 30 feet of defensible space around the home. Remove dead vegetation, wood piles near the house, and flammable decking materials.' },
          { title: 'Inspect and Seal Foundation for Moisture', frequency: 'Annual', notes: 'PNW homes are prone to moisture intrusion and mold. Check foundation walls and crawl space for dampness. Install a vapor barrier in crawl space if not present. Run a dehumidifier in damp areas.' },
          { title: 'Test and Clean Dryer Vent', frequency: 'Annual', notes: 'Lint buildup in dryer vents is a fire hazard, especially when homes are sealed tight in wet weather. Clean the entire vent run annually. Ensure the exterior vent cap opens and closes freely.' },
          { title: 'Check for Mold in Attic and Crawl Space', frequency: 'Annual', notes: 'PNW humidity makes attics and crawl spaces prime mold locations. Inspect each spring for black or white mold growth. Ensure attic vents are clear and crawl space has proper vapor barrier and ventilation.' },
          { title: 'Earthquake Preparedness Check', frequency: 'Annual', notes: 'The PNW sits on the Cascadia Subduction Zone. Strap water heater and heavy furniture to walls. Store a 2-week emergency supply. Know your drop-cover-hold-on plan. Have cash and important documents accessible.' },
        ],
      },
      southwest: {
        name: 'Southwest — Extreme Heat, Drought & Flash Flood Prep',
        tips: 'The Southwest faces extreme summer heat, drought conditions, flash floods, and dust storms (haboobs). Prepare your home for both scorching dry seasons and intense monsoon storms.',
        tasks: [
          { title: 'HVAC Pre-Summer Tune-Up', frequency: 'Annual', notes: 'Schedule AC service each March before summer heat hits. In Phoenix and surrounding areas, temperatures exceed 110°F — a failing AC is a life-safety emergency. Check refrigerant, coils, and capacitor.' },
          { title: 'Inspect and Clean Evaporative Cooler', frequency: 'Annual', notes: 'If using a swamp cooler, replace pads, clean the reservoir, and check the pump and motor each spring. Switch to AC when humidity rises during monsoon season (July-September) — swamp coolers don\'t work in humid conditions.' },
          { title: 'Monsoon Season Prep', frequency: 'Annual', notes: 'Before July monsoon season, clear gutters, check roof drainage, and inspect window and door seals. Monsoon storms produce intense rainfall that flat or low-slope roofs can\'t drain fast enough, causing ponding and leaks.' },
          { title: 'Flash Flood Awareness and Prep', frequency: 'Annual', notes: 'Know if your property is in a wash or flood-prone area (FEMA flood map). Never drive through flooded washes — "turn around, don\'t drown." Keep sandbags accessible if near a wash. Check drainage around the home.' },
          { title: 'Dust Storm (Haboob) Preparedness', frequency: 'Annual', notes: 'Seal gaps around windows and doors to minimize dust intrusion. Change HVAC filters after major dust storms. Keep a spare set of MERV-13 filters on hand. Replace cabin air filters in vehicles after haboob season.' },
          { title: 'Water Conservation and Irrigation Audit', frequency: 'Annual', notes: 'Southwest water restrictions are increasingly common. Audit your irrigation system for leaks and over-watering. Convert to drip irrigation and drought-tolerant landscaping. Know your municipality\'s current water restrictions.' },
          { title: 'Inspect Stucco and Exterior Walls', frequency: 'Annual', notes: 'Southwest homes are predominantly stucco. Inspect annually for cracks — intense heat and monsoon moisture cause expansion and contraction that leads to cracking. Fill small cracks with elastomeric caulk to prevent water intrusion.' },
          { title: 'Wildfire Defensible Space', frequency: 'Annual', notes: 'If in a wildland-urban interface area (foothills, rural areas), maintain 100 feet of defensible space. Remove dead vegetation, palm fronds, and wood piles near the home. Clear pine needles from roof and gutters.' },
          { title: 'Inspect Roof Coating and Flat Roof Drains', frequency: 'Annual', notes: 'Many Southwest homes have flat or low-slope roofs with elastomeric coatings. Inspect for bubbling, cracking, or peeling each spring. Clear roof drains before monsoon season to prevent ponding water, which leads to leaks and structural damage.' },
          { title: 'Heat Emergency Plan', frequency: 'Annual', notes: 'Know your nearest cooling center (public library, community center, mall). Have a plan for power outages during heat waves. Check on elderly neighbors. Keep at least a 3-day water supply (more than standard due to extreme heat).' },
        ],
      },
      west: {
        name: 'West / California — Wildfire, Earthquake & Drought Prep',
        tips: 'California homeowners face three major threats: wildfires, earthquakes, and prolonged drought. Preparing for all three requires year-round attention — fire season now runs nearly year-round in many areas.',
        tasks: [
          { title: 'Wildfire Defensible Space — Zone 1 (0-30 ft)', frequency: 'Annual', notes: 'Clear the area within 30 feet of the home of dead plants, dry leaves, and flammable materials. Keep grass mowed to 4 inches or less. Remove wood piles and propane tanks away from the structure. Cal Fire requires this by law in State Responsibility Areas.' },
          { title: 'Wildfire Defensible Space — Zone 2 (30-100 ft)', frequency: 'Annual', notes: 'In the 30-100 foot zone, space plants and trees to reduce fire spread. Remove ladder fuels (shrubs under trees). Keep debris cleared. This zone slows fire and gives firefighters room to work.' },
          { title: 'Harden Your Home Against Embers', frequency: 'Annual', notes: 'Ember intrusion — not direct flame — causes most home ignitions during wildfires. Install 1/16-inch mesh screens on all vents and eaves. Replace wood decking with composite or concrete. Clear gutters and install gutter guards. Check roof and walls for gaps.' },
          { title: 'Create a Go Bag and Evacuation Plan', frequency: 'Annual', notes: 'Prepare a go bag with: copies of important documents, medications (2-week supply), cash, phone chargers, change of clothes, and water. Know your evacuation routes and sign up for county emergency alerts (e.g., AlertSCC, AlertSF, Nixle).' },
          { title: 'Earthquake Preparedness', frequency: 'Annual', notes: 'Strap water heater, refrigerator, and tall furniture to walls. Store 2 weeks of food and water. Know how to shut off gas at the meter (keep wrench nearby). Bolt the home to its foundation if not already done (cripple wall or soft-story retrofit).' },
          { title: 'Check Earthquake Gas Shutoff Valve', frequency: 'Annual', notes: 'Consider installing an automatic seismic gas shutoff valve if not already present. After any significant earthquake, inspect for gas leaks by smell before re-entering. Know location of the manual shutoff and keep a wrench accessible.' },
          { title: 'Drought and Water Conservation Audit', frequency: 'Annual', notes: 'Check for leaks in irrigation system and indoor plumbing. Convert to drought-tolerant landscaping. Know your water district\'s current stage restrictions. Install a smart irrigation controller that adjusts for rainfall and evapotranspiration.' },
          { title: 'Air Quality — Wildfire Smoke Plan', frequency: 'Annual', notes: 'Stock N95 respirators for each family member. Upgrade HVAC filter to MERV-13. Designate a "clean room" with a portable air purifier (HEPA). Know how to recirculate air in your car. Monitor AirNow.gov during fire events.' },
          { title: 'Inspect Chimney and Clear Roof of Debris', frequency: 'Annual', notes: 'Have chimney professionally cleaned before fire season. Clear pine needles, leaves, and debris from roof and gutters — these are prime ignition points for ember showers. Install metal spark arrestor cap on chimney.' },
          { title: 'Review Homeowner\'s Insurance for Fire Coverage', frequency: 'Annual', notes: 'Many California insurers have pulled out of high-risk areas. Verify your policy is active and covers wildfire at full replacement cost. If dropped, explore the FAIR Plan as a last resort. Document all belongings with video annually.' },
        ],
      },
    },
  },
}
